server:
  port: 8000

    
spring:
  servlet:
    multipart:
      enabled: true
      location: temp123
      file-size-threshold: 15MB
      max-file-size: 15MB
      max-request-size: 200MB

  datasource:
    url: jdbc:postgresql://localhost:5432/projetstage2021
    
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
